import { colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const adolescenteConcluirMissaoStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  header: {
    backgroundColor: "#08A23D",
    paddingHorizontal: 14,
    paddingBottom: 18,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.86)",
    fontSize: 14,
    marginTop: 4,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingTop: 16,
    gap: 14,
  },
  confirmCard: {
    marginHorizontal: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E9EAF0",
    shadowColor: "#101828",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  confirmIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#DDFBE8",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  confirmIconInner: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#67D88E",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmTitle: {
    color: "#101828",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 8,
  },
  confirmText: {
    color: "#667085",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  rewardCard: {
    marginHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "#08C443",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  rewardLabel: {
    color: "#E8FFE3",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 4,
  },
  rewardValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "700",
  },
  card: {
    marginHorizontal: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E9EAF0",
    shadowColor: "#101828",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  cardTitle: {
    color: "#344054",
    fontSize: 14,
    fontWeight: "600",
  },
  commentInput: {
    minHeight: 110,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D0D5DD",
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: "#101828",
    fontSize: 14,
    lineHeight: 21,
    backgroundColor: "#FFFFFF",
  },
  photoDropzone: {
    minHeight: 120,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "#D0D5DD",
    overflow: "hidden",
    backgroundColor: "#FCFCFD",
  },
  photoPlaceholder: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  photoPlaceholderText: {
    color: "#667085",
    fontSize: 14,
    fontWeight: "500",
  },
  photoPreview: {
    width: "100%",
    height: 160,
  },
  photoOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingVertical: 10,
    backgroundColor: "rgba(17,24,39,0.58)",
    alignItems: "center",
  },
  photoOverlayText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  tipCard: {
    marginHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  tipText: {
    flex: 1,
    color: "#2563EB",
    fontSize: 13,
    lineHeight: 18,
  },
  footerRow: {
    marginHorizontal: 16,
    flexDirection: "row",
    gap: 10,
  },
  footerButton: {
    flex: 1,
    minHeight: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  cancelButton: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D0D5DD",
  },
  cancelButtonText: {
    color: "#344054",
    fontSize: 16,
    fontWeight: "500",
  },
  submitButton: {
    backgroundColor: "#08B43E",
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  notFoundContainer: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  notFoundBack: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    marginBottom: 20,
  },
  notFoundBackText: {
    color: "#101828",
    fontSize: 14,
    fontWeight: "600",
  },
  notFoundTitle: {
    color: "#101828",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 8,
  },
  notFoundText: {
    color: "#667085",
    fontSize: 15,
    lineHeight: 22,
  },
});
