import { colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const adolescenteDetalhesMissaoStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F3F4F6",
  },
  header: {
    paddingHorizontal: 12,
    paddingBottom: 18,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 32,
    fontWeight: "700",
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 14,
    marginTop: 2,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingTop: 18,
    gap: 14,
  },
  rewardCard: {
    marginHorizontal: 16,
    backgroundColor: "#06C755",
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 20,
    alignItems: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  rewardLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rewardLabel: {
    color: "#E8FFE3",
    fontSize: 16,
    fontWeight: "600",
  },
  rewardValue: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 10,
  },
  rewardBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  rewardBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  missionCard: {
    marginHorizontal: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#E9EAF0",
    shadowColor: "#0F172A",
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 3,
  },
  missionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  missionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5EDFF",
  },
  missionTitle: {
    flex: 1,
    color: "#1F2937",
    fontSize: 18,
    fontWeight: "700",
  },
  statusPill: {
    alignSelf: "flex-start",
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F3E8FF",
  },
  statusPillText: {
    color: "#A855F7",
    fontSize: 12,
    fontWeight: "600",
  },
  infoCard: {
    marginHorizontal: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#E6EAF0",
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  infoCardHighlighted: {
    backgroundColor: "#EFF6FF",
    borderColor: "#B6D4FE",
  },
  infoHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  infoTitle: {
    color: "#344054",
    fontSize: 15,
    fontWeight: "700",
  },
  descriptionText: {
    color: "#475467",
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 12,
  },
  criteriaList: {
    gap: 10,
  },
  criteriaRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  criteriaDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.brand.purple,
    marginTop: 7,
  },
  criteriaText: {
    flex: 1,
    color: "#344054",
    fontSize: 14,
    lineHeight: 21,
  },
  infoText: {
    color: "#344054",
    fontSize: 14,
    lineHeight: 22,
  },
  tipCard: {
    marginHorizontal: 16,
    borderRadius: 18,
    padding: 18,
  },
  tipHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  tipTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  tipText: {
    color: "#FFF7F9",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
  },
  completeButton: {
    marginHorizontal: 16,
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: "#00C853",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#16A34A",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  completeButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  notFoundContainer: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  notFoundBack: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "flex-start",
    marginBottom: 20,
  },
  notFoundBackText: {
    color: colors.neutral.text,
    fontSize: 14,
    fontWeight: "600",
  },
  notFoundTitle: {
    color: "#101828",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 8,
  },
  notFoundText: {
    color: "#667085",
    fontSize: 15,
    lineHeight: 22,
  },
});
