import { colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const adolescenteExtratoStyles = StyleSheet.create({
  statementScreen: { flex: 1, backgroundColor: "#F5F5F7" },
  scrollView: { flex: 1 },
  statementScrollContent: { paddingHorizontal: 0, paddingBottom: 24, gap: 14 },
  statementHeader: { paddingHorizontal: 14, paddingBottom: 18 },
  statementBackButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    marginLeft: -4,
  },
  statementHeaderTitle: { color: "#FFF", fontSize: 30, fontWeight: "700" },
  statementHeaderSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 14,
    marginTop: 2,
  },
  statementBalanceCard: {
    marginHorizontal: 16,
    marginTop: 4,
    backgroundColor: "#06C443",
    borderRadius: 14,
    padding: 16,
  },
  statementBalanceTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  statementBalanceLabel: { color: "#E0FCE8", fontSize: 13, fontWeight: "600" },
  statementBalanceValue: { color: "#FFF", fontSize: 24, fontWeight: "700" },
  statementFilterCard: {
    marginHorizontal: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 14,
    padding: 6,
    borderWidth: 1,
    borderColor: "#E7EAF0",
    flexDirection: "row",
    gap: 6,
  },
  statementFilterButton: {
    flex: 1,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statementFilterButtonActive: { backgroundColor: "#3F5EFB" },
  statementFilterText: { color: "#344054", fontSize: 13, fontWeight: "600" },
  statementFilterTextActive: { color: "#FFF" },
  statementList: { gap: 10, paddingHorizontal: 16 },
  statementItemCard: {
    backgroundColor: colors.neutral.white,
    borderRadius: 14,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ECEEF4",
    shadowColor: "#0F172A",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  statementItemIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  statementItemContent: { flex: 1, paddingRight: 10 },
  statementItemTitle: { color: "#111827", fontSize: 14, fontWeight: "600" },
  statementItemDate: { color: "#94A3B8", fontSize: 12, marginTop: 4 },
  statementItemMeta: { alignItems: "flex-end" },
  statementItemValue: { color: "#22C55E", fontSize: 14, fontWeight: "700" },
  statementItemCategory: { color: "#94A3B8", fontSize: 12, marginTop: 4 },
  statementSummaryCard: {
    marginHorizontal: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E7EAF0",
  },
  statementSummaryTitle: {
    color: "#344054",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 14,
  },
  statementSummaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  statementSummaryLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statementSummaryLabel: { color: "#475467", fontSize: 14 },
  statementSummaryValue: { color: "#16A34A", fontSize: 14, fontWeight: "700" },
  statementSummaryDivider: {
    height: 1,
    backgroundColor: "#EAECF0",
    marginVertical: 4,
  },
  statementSummaryTotalLabel: {
    color: "#344054",
    fontSize: 16,
    fontWeight: "600",
  },
  statementSummaryTotalValue: {
    color: "#16A34A",
    fontSize: 20,
    fontWeight: "700",
  },
});
