import { colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const adolescenteHomeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F5F7" },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 10, paddingBottom: 32, gap: 14 },
  heroCard: {
    marginHorizontal: -10,
    marginTop: 0,
    paddingHorizontal: 18,
    paddingBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  headerUserRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  headerAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerAvatarEmoji: { fontSize: 14, fontWeight: "700", color: "#FFF" },
  headerName: { color: "#FFF", fontSize: 24, fontWeight: "700" },
  headerSubtitle: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 14,
    marginTop: 2,
  },
  notificationButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  notificationBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#FF4D4F",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 3,
    right: 1,
    paddingHorizontal: 4,
  },
  notificationBadgeText: { color: "#FFF", fontSize: 10, fontWeight: "700" },
  balanceCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  balanceLabel: { color: "#FDE7F3", fontSize: 15, marginBottom: 6 },
  balanceValue: {
    color: "#FFF",
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 14,
  },
  progressTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.22)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#22C55E",
  },
  progressText: {
    color: "#FFF",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "right",
    marginTop: 8,
  },
  sectionCard: {
    marginHorizontal: 0,
    backgroundColor: colors.neutral.white,
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#EFEFF3",
    shadowColor: "#12051F",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: { color: "#231942", fontSize: 18, fontWeight: "700" },
  sectionMeta: { color: "#6B7280", fontSize: 13, fontWeight: "600" },
  missionList: { gap: 10 },
  missionCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 16,
    backgroundColor: "#FFF7FC",
    borderWidth: 1,
    borderColor: "#F7E7F3",
  },
  rowIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.neutral.white,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  rowContent: { flex: 1, paddingRight: 12 },
  rowTitle: { fontSize: 16, fontWeight: "600", color: "#23213D" },
  rowSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: "#A855F7",
    fontWeight: "500",
  },
  rowValue: { fontSize: 16, fontWeight: "700", color: "#22C55E" },
  actionsRow: { flexDirection: "row", gap: 10, paddingHorizontal: 0 },
  actionCard: {
    flex: 1,
    minHeight: 86,
    borderRadius: 16,
    backgroundColor: colors.neutral.white,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#ECECF2",
    shadowColor: "#12051F",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  actionIcon: { alignItems: "center", justifyContent: "center" },
  actionLabel: { fontSize: 13, color: "#2D264B", fontWeight: "600" },
  tipCard: { marginHorizontal: 0, borderRadius: 16, padding: 16 },
  tipHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  tipTitle: { color: "#FFF", fontSize: 16, fontWeight: "700" },
  tipText: { color: "#F8FBFF", fontSize: 15, lineHeight: 22 },
});
