import { StyleSheet } from "react-native";

export const adolescenteNotificacaoAprovadaStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#09B63E",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    gap: 16,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  hero: {
    alignItems: "center",
    paddingTop: 10,
    gap: 10,
  },
  heroIconWrap: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
    textAlign: "center",
  },
  heroSubtitle: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
  },
  missionTitle: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
  },
  card: {
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    padding: 18,
    gap: 14,
  },
  financialLabel: {
    color: "#475467",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  financialValue: {
    color: "#08A63B",
    fontSize: 28,
    fontWeight: "800",
    textAlign: "center",
  },
  divider: {
    height: 1,
    backgroundColor: "#E4E7EC",
  },
  moneyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  moneyRowLabel: {
    color: "#344054",
    fontSize: 15,
    fontWeight: "500",
  },
  moneyRowValue: {
    color: "#101828",
    fontSize: 18,
    fontWeight: "700",
  },
  moneyRowHighlight: {
    color: "#08A63B",
  },
  xpCard: {
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  xpIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FACC15",
    alignItems: "center",
    justifyContent: "center",
  },
  xpLabel: {
    color: "rgba(255,255,255,0.86)",
    fontSize: 14,
    fontWeight: "600",
  },
  xpValue: {
    color: "#FFFFFF",
    fontSize: 28,
    fontWeight: "800",
  },
  infoCard: {
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.16)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    padding: 16,
    gap: 10,
  },
  infoTitle: {
    color: "#D1FADF",
    fontSize: 14,
    fontWeight: "700",
  },
  infoText: {
    color: "#FFFFFF",
    fontSize: 16,
    lineHeight: 24,
  },
  ctaButton: {
    minHeight: 58,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  ctaText: {
    color: "#047857",
    fontSize: 16,
    fontWeight: "700",
  },
  stateContainer: {
    flex: 1,
    backgroundColor: "#09B63E",
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  stateTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  stateText: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 15,
    textAlign: "center",
    lineHeight: 22,
  },
});
