import { colors } from "@/constants/colors";
import { StyleSheet } from "react-native";

export const adolescentePerfilStyles = StyleSheet.create({
  profileScreen: { flex: 1, backgroundColor: "#F5F5F7" },
  scrollView: { flex: 1 },
  profileScrollContent: { paddingBottom: 24, gap: 12 },
  profileHero: {
    alignItems: "center",
    paddingHorizontal: 18,
    paddingBottom: 44,
  },
  profileAvatarWrap: { position: "relative", marginTop: 4, marginBottom: 10 },
  profileAvatar: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileAvatarText: { color: "#FFF", fontSize: 26, fontWeight: "700" },
  profileAvatarEditButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: -2,
    bottom: 2,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  profileName: { color: "#FFF", fontSize: 17, fontWeight: "700" },
  profileHandle: { color: "rgba(255,255,255,0.9)", fontSize: 13, marginTop: 4 },
  profileStatsCard: {
    marginHorizontal: 14,
    marginTop: -30,
    backgroundColor: colors.neutral.white,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#ECEEF3",
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  profileStatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  profileStatItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  profileStatIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
  },
  profileStatValue: {
    color: "#101828",
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 24,
  },
  profileStatLabel: { color: "#667085", fontSize: 11, textAlign: "center" },
  profileSectionCard: {
    marginHorizontal: 14,
    backgroundColor: colors.neutral.white,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#ECEEF3",
    shadowColor: "#0F172A",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  profileSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  profileSectionTitle: { color: "#344054", fontSize: 14, fontWeight: "600" },
  profileSectionMeta: {
    marginLeft: "auto",
    color: "#98A2B3",
    fontSize: 12,
    fontWeight: "600",
  },
  profileBadgeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  profileBadgeCard: {
    width: "48%",
    minHeight: 124,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  profileBadgeCardActive: {
    backgroundColor: "#FFFBEB",
  },
  profileBadgeCardInactive: { backgroundColor: "#F8FAFC", opacity: 0.55 },
  profileBadgeIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    marginBottom: 10,
  },
  profileBadgeLabel: {
    color: "#344054",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  profileBadgeDescription: {
    color: "#667085",
    fontSize: 11,
    lineHeight: 16,
    marginTop: 6,
    textAlign: "center",
  },
  profileBadgeLabelInactive: { color: "#98A2B3" },
  profileBadgeDescriptionInactive: { color: "#98A2B3" },
  profileEvolutionCard: {
    minHeight: 168,
    justifyContent: "flex-end",
    paddingTop: 18,
  },
  profileEvolutionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  profileEvolutionItem: { alignItems: "center", gap: 6, flex: 1 },
  profileEvolutionValue: { color: "#98A2B3", fontSize: 10, fontWeight: "600" },
  profileEvolutionBarTrack: {
    width: 26,
    height: 82,
    borderRadius: 13,
    backgroundColor: "#F3F4F6",
    justifyContent: "flex-end",
    overflow: "hidden",
  },
  profileEvolutionBarFill: {
    width: "100%",
    minHeight: 10,
    borderRadius: 13,
    backgroundColor: "#22C55E",
  },
  profileEvolutionWeek: { color: "#344054", fontSize: 12, fontWeight: "600" },
  profileEvolutionAccumulated: {
    color: "#98A2B3",
    fontSize: 10,
    fontWeight: "600",
  },
  profileEvolutionCaption: {
    textAlign: "center",
    color: "#98A2B3",
    fontSize: 11,
    marginTop: 18,
  },
  profileEmptyText: {
    color: "#98A2B3",
    fontSize: 13,
    lineHeight: 18,
  },
  profileSettingsList: { marginTop: 8 },
  profileSettingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: "#F2F4F7",
  },
  profileSettingLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  profileSettingIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  profileSettingLabel: { color: "#101828", fontSize: 14, fontWeight: "500" },
  profileLogoutButton: {
    marginHorizontal: 14,
    marginTop: 4,
    backgroundColor: "#EF4444",
    borderRadius: 14,
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  profileLogoutText: { color: "#FFF", fontSize: 15, fontWeight: "700" },
});
